version: "3"

services:

  runtime-setup:
    image: swift-nio:18.04-5.0
    build:
      args:
        ubuntu_version: "18.04"
        swift_version: "5.0"
        swift_flavour: "DEVELOPMENT-SNAPSHOT-2019-02-20-a"
        swift_builds_suffix: "branch"
        skip_ruby_from_ppa: "true"

  unit-tests:
    image: swift-nio:18.04-5.0
    command: /bin/bash -cl "swift test -Xswiftc -warnings-as-errors -Xswiftc -DNIO_CI_BUILD"

  integration-tests:
    image: swift-nio:18.04-5.0
    environment:
      - MAX_ALLOCS_ALLOWED_1000_reqs_1_conn=45750
      - MAX_ALLOCS_ALLOWED_1_reqs_1000_conn=692050
      - MAX_ALLOCS_ALLOWED_ping_pong_1000_reqs_1_conn=4600
      - MAX_ALLOCS_ALLOWED_bytebuffer_lots_of_rw=2100
      - MAX_ALLOCS_ALLOWED_future_lots_of_callbacks=99100

  test:
    image: swift-nio:18.04-5.0
    command: /bin/bash -cl "swift test -Xswiftc -warnings-as-errors -Xswiftc -DNIO_CI_BUILD && ./scripts/integration_tests.sh"
    environment:
      - MAX_ALLOCS_ALLOWED_1000_reqs_1_conn=45750
      - MAX_ALLOCS_ALLOWED_1_reqs_1000_conn=692050
      - MAX_ALLOCS_ALLOWED_ping_pong_1000_reqs_1_conn=4600
      - MAX_ALLOCS_ALLOWED_bytebuffer_lots_of_rw=2100
      - MAX_ALLOCS_ALLOWED_future_lots_of_callbacks=99100

  echo:
    image: swift-nio:18.04-5.0

  http:
    image: swift-nio:18.04-5.0
